= Ong Wei Sheng - Project Portfolio
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: Personal Trainer Pro Application

---

== Overview

Personal Trainer Pro is a desktop application used by personal trainers and their clients to keep track of their fitness journey. The user interacts with it using a CLI, and it has a GUI created with JavaFX. It is written in Java, and has about 10 kLoC.

== Summary of contributions

* *Major enhancement*: added *integrated Google Calendar Services*
** What it does: Through the 'calendar' and 'addEvent' command, users can display their Google Calendar within the application, and also add new events to their Google Calendar through CLI.
** Justification: This feature improves the product significantly as it allows users to have increased ease in the management of their schedule. It can be troublesome to have to switch between applications when planning one's schedule. This feature allows the user to do everything within the application itself, allowing them to finish planning quicker and more efficiently.
** Highlights: This enhancement touched on all the different components of the code from User Interface to the Model component. Therefore, it required a deep understanding of how the different component interacts with one another. Also, since Google Calendar is integrated, it requires knowledge on how the Google Calendar API works and how to set it up, making it very challenging to implement.
** Credits: Google Calendar API was used to allow Google Calendar services to be integrated into the application.

* *Minor enhancement*: added a weight attribute that stores the users' weight, which is essential since this is a fitness application.

* *Code contributed*: [https://github.com[Functional code]] [https://github.com[Test code]] _{give links to collated code files}_

* *Other contributions*:

** Project management:
***
** Enhancements to existing features:
*** Updated the GUI color scheme (Pull requests https://github.com/CS2103JAN2018-F12-B2/main/pull/107)
*** Wrote additional tests for existing features to increase coverage from 85% to 88% (Pull requests https://github.com/CS2103JAN2018-F12-B2/main/pull/90)
** Documentation:
*** Update user and developer guide: https://github.com/CS2103JAN2018-F12-B2/main/pull/100
** Community:
*** Reported bugs and suggestions for other teams in the class (examples: https://github.com/CS2103JAN2018-W09-B1/main/issues/134, https://github.com/CS2103JAN2018-W09-B1/main/issues/130, https://github.com/CS2103JAN2018-W09-B1/main/issues/126)
** Tools:
*** Integrated a third party service (Google Calendar) to the project (https://github.com/CS2103JAN2018-F12-B2/main/pull/56)

_{you can add/remove categories in the list above}_

== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=calendar]

include::../UserGuide.adoc[tag=addEvent]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=GoogleCalendarApi]

---
